- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install Zephyr Requirements
  apt: name={{ item }} state=latest
  with_items:
    - git
    - make
    - gcc
    - gcc-multilib
    - g++
    - libc6-dev-i386
    - g++-multilib
    - libncurses5-dev
  become: yes

# create a the downloads directory if it isn't there
- file: path=/vagrant/downloads state=directory

# Specifying destination file name, since having a destination directory makes it re-download the file every time
- name: Download Zephyr SDK
  get_url:  url=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.9/zephyr-sdk-0.9-setup.run
            dest=/vagrant/downloads/zephyr-sdk-0.9-setup.run
            mode=0775
            force=no
            validate_certs=no

# Need to echo install directory since it always prompts for it and we can't pass as an argument
- name: Install SDK
  shell: echo '/home/vagrant/zephyr-sdk/' | /vagrant/downloads/zephyr-sdk-0.9-setup.run
  args:
    creates: /home/vagrant/zephyr-sdk

- name: copy ~/.zephyrrc
  copy: src=roles/common/files/.zephyrrc dest=/home/vagrant

- name: Check if zephyr-project exists
  stat: path=/vagrant/zephyr-project
  register: zephyr_project_dir

- name: clone zephyr-project repo
  when: not zephyr_project_dir.stat.exists
  git:  repo=https://gerrit.zephyrproject.org/r/zephyr
        dest=/vagrant/zephyr-project
        version=tags/v1.7.0

- name: Add zephyr config to ~/.profile
  lineinfile: dest=/home/vagrant/.profile line='source /vagrant/zephyr-project/zephyr-env.sh'
