- name: update apt cache
  apt: update_cache=yes
  become: yes

- name: Install Zephyr Requirements
  apt: name={{ item }} state=latest
  with_items:
    - git
    - make
    - gcc
    - gcc-multilib
    - g++
    - libc6-dev-i386
    - g++-multilib
    - libncurses5-dev
  become: yes

# create a the downloads directory if it isn't there
- file: path=/vagrant/downloads state=directory

# Specifying destination file name, since having a destination directory makes it re-download the file every time
- name: Download Zephyr SDK
  get_url:  url=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.7.5-i686/zephyr-sdk-0.7.5-i686-setup.run
            dest=/vagrant/downloads/zephyr-sdk-0.7.5-i686-setup.run
            mode=0775
            force=no

# Need to echo install directory since it always prompts for it and we can't pass as an argument
- name: Install SDK
  shell: echo '/home/vagrant/zephyr-sdk/' | /vagrant/downloads/zephyr-sdk-0.7.5-i686-setup.run
  args:
    creates: /home/vagrant/zephyr-sdk 

- name: copy ~/.zephyrrc
  copy: src=roles/common/files/.zephyrrc dest=/home/vagrant

- name: clone zephyr-project repo
  git:  repo=https://gerrit.zephyrproject.org/r/zephyr
        dest=/home/vagrant/zephyr-project
        version=tags/v1.2.0
